### ISSUE TITLE
Sayfa açıldığında home yüklenmiyor

### ISSUE THREAD

**Issue by gokhanozdemir** [mburakaltiparmak/ecommerce#11]
https://ecommerce-sage-xi.vercel.app/
Safari Mac OSx 
<img width="1483" alt="image" src="https://github.com/mburakaltiparmak/ecommerce/assets/8511119/8baa9aac-8743-43ac-91a0-dbf6b62c6bce">

**Comment by mburakaltiparmak** [comment]
redirectte problem yaşamıştım da kaldırmıştım. mevcut issue'nun son commitinde yeniden eklendi.
