### ISSUE TITLE
T9: Fetch Categories

### ISSUE THREAD

**Issue by mburakaltiparmak** [mburakaltiparmak/ecommerce#13]
- [x] Fetch categories by **thunk action** and store it in the **gobal reducer**
- [x] endpoint “/categories“
- [x] list categories on the screen
- [x] categories should be link
- [x] on click it should navigate to “/shopping/:gender/:category”
- [x] top 5 categories should be listed on the screen with images regarding “rating” value
- [x] all categories should be listed in drop down menu on header

**Comment by mburakaltiparmak** [comment]
t9 tamamlandı. yeni datalarla beraber oluşan görüntü mobile uygun olacak şekilde güncellendi.

**Comment by erhanfirat** [comment]
shop sayfası açılmalı
menü kadın erkek olarak yanyana iki kolonda gösterilmeli

**Comment by mburakaltiparmak** [comment]
Shop butonu hover durumunda kategorileri kadın ve erkek olarak yan yana iki kolonda gösteriyor. onClick durumunda bağlı olduğu link üzerinden /shop adresine yönlendiriyor.
